### ISSUE TITLE
QRNG Chains and Providers into one section

### ISSUE THREAD

**Issue by vanshwassan** [api3dao/vitepress-docs#708]
https://docs.api3.org/reference/qrng/chains.html
https://docs.api3.org/reference/qrng/providers.html

People usually have difficulty following up with different chains and providers when using QRNG. This is one of the issues we noticed with the recent hackathons with users getting confused with QRNG Airnode providers and `AirnodeRrpV0` addresses.

I would guess the solution to this would be to have a single section where people can select their chain from a dropdown and list all the current providers on that certain chain along with the `AirnodeRrpV0` address. So all they would want to do is select the chain and use one of the listed providers.

@dcroote @wkande @Ashar2shahid ?

**Comment by dcroote** [comment]
Great point on a better UX being a single location that contains all necessary data for using QRNG on a given chain with a given provider rather than how those data are currently split between two locations (`AirnodeRrpV0` address on one page, provider details on another).

A dropdown selection would also save on scrolling through lots of chain and provider details the user isn't interested in and would reduce the likelihood of mixing something up.

👍

**Comment by wkande** [comment]
QRNG is deprecated
